// Reads Tailwind's default palettes (v1, v3 and v4) from the installed packages
// and writes them to src/tailwind-palette.ts as OKLCH. Run with
// `npm run palette` after upgrading any of the tailwindcss dev dependencies.
import { readFileSync, writeFileSync } from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join } from 'node:path'
import { converter } from 'culori'

const require = createRequire(import.meta.url)
const toOklch = converter('oklch')
const round = (value, digits) => Number(value.toFixed(digits))

/** Converts a hex color to [l, c, h] with the same precision Tailwind v4 uses */
function hexToOklch(hex) {
  const { l, c = 0, h } = toOklch(hex)
  return [round(l, 4), round(c, 3), h === undefined ? null : round(h, 3)]
}

/** Replaces missing hues (colorless shades) with the nearest shade's hue, or 0 */
function fillHues(shades) {
  for (const [index, shade] of shades.entries()) {
    if (shade[2] !== null) continue
    const nearest = shades
      .map((other, otherIndex) => ({ other, distance: Math.abs(otherIndex - index) }))
      .filter(({ other }) => other[2] !== null)
      .sort((a, b) => a.distance - b.distance)[0]
    shade[2] = nearest?.other[2] ?? 0
  }
  return shades
}

/** Keeps colors that define every shade, in order */
function completeColors(colors, shades) {
  return Object.fromEntries(
    Object.entries(colors)
      .filter(([, byShade]) => shades.every((shade) => byShade[shade]))
      .map(([name, byShade]) => [name, fillHues(shades.map((shade) => byShade[shade]))]),
  )
}

/**
 * A reference palette: OKLCH numbers for the math, and Tailwind's own strings
 * (exactly as Tailwind writes them) for showing a Tailwind color.
 */
function palette(pkg, shades, colors, values) {
  const complete = completeColors(colors, shades)
  return {
    version: require(`${pkg}/package.json`).version,
    shades,
    colors: complete,
    values: Object.fromEntries(
      Object.keys(complete).map((name) => [name, shades.map((shade) => values[name][shade].toLowerCase())]),
    ),
  }
}

// v4: CSS variables in theme.css, already in OKLCH (hue is `none` for colorless shades)
function readV4() {
  const pkg = 'tailwindcss'
  const css = readFileSync(join(dirname(require.resolve(`${pkg}/package.json`)), 'theme.css'), 'utf8')
  const pattern = /--color-([a-z]+)-(\d+):\s*(oklch\(([\d.]+)%\s+([\d.]+)\s+([\d.]+|none)\))/g
  const colors = {}
  const values = {}
  for (const [, name, shade, value, l, c, h] of css.matchAll(pattern)) {
    colors[name] ??= {}
    values[name] ??= {}
    colors[name][shade] = [round(Number(l) / 100, 4), Number(c), h === 'none' ? null : Number(h)]
    values[name][shade] = value
  }
  const shades = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]
  return palette(pkg, shades, colors, values)
}

// v3: hex values in `tailwindcss/colors`. Deprecated aliases are getters that
// log a warning, so only plain data properties are read.
function readV3() {
  const pkg = 'tailwindcss-v3'
  const all = require(`${pkg}/colors`)
  const colors = {}
  const values = {}
  for (const [name, descriptor] of Object.entries(Object.getOwnPropertyDescriptors(all))) {
    if (!('value' in descriptor) || typeof descriptor.value !== 'object') continue
    colors[name] = Object.fromEntries(
      Object.entries(descriptor.value).map(([shade, hex]) => [shade, hexToOklch(hex)]),
    )
    values[name] = descriptor.value
  }
  const shades = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950]
  return palette(pkg, shades, colors, values)
}

// v1: hex values in the default config stub
function readV1() {
  const pkg = 'tailwindcss-v1'
  const all = require(`${pkg}/stubs/defaultConfig.stub.js`).theme.colors
  const colors = {}
  const values = {}
  for (const [name, value] of Object.entries(all)) {
    if (typeof value !== 'object') continue
    colors[name] = Object.fromEntries(
      Object.entries(value).map(([shade, hex]) => [shade, hexToOklch(hex)]),
    )
    values[name] = value
  }
  const shades = [100, 200, 300, 400, 500, 600, 700, 800, 900]
  return palette(pkg, shades, colors, values)
}

function toSource(constName, { version, shades, colors, values }) {
  const body = Object.entries(colors)
    .map(
      ([name, oklch]) =>
        `    ${name}: [\n${oklch.map((v) => `      [${v.join(', ')}],`).join('\n')}\n    ],`,
    )
    .join('\n')
  const strings = Object.entries(values)
    .map(([name, list]) => `    ${name}: [${list.map((v) => `'${v}'`).join(', ')}],`)
    .join('\n')
  return `/** Default palette of tailwindcss@${version} */
export const ${constName}: ReferencePalette = {
  shades: [${shades.join(', ')}],
  colors: {
${body}
  },
  values: {
${strings}
  },
}`
}

const palettes = { PALETTE_V4: readV4(), PALETTE_V3: readV3(), PALETTE_V1: readV1() }

writeFileSync(
  new URL('../src/tailwind-palette.ts', import.meta.url),
  `// Generated by scripts/extract-palette.mjs. Do not edit.
// Each color lists its shades in order as OKLCH [lightness 0-1, chroma, hue],
// and in 'values' as Tailwind's own strings.

export type Oklch = readonly [l: number, c: number, h: number]

export type ReferencePalette = {
  shades: readonly number[]
  colors: Record<string, readonly Oklch[]>
  /** The same colors exactly as Tailwind writes them: oklch() in v4, hex before */
  values: Record<string, readonly string[]>
}

${Object.entries(palettes)
  .map(([name, palette]) => toSource(name, palette))
  .join('\n\n')}
`,
)

for (const [name, { version, colors }] of Object.entries(palettes)) {
  console.log(`${name}: ${Object.keys(colors).length} colors from tailwindcss@${version}`)
}
